#!/usr/bin/env python3
"""Research Agora feedback client (RFC-0001).

Opt-in, content-free usage capture with a mandatory review gate.
Stdlib-only; every subcommand is safe to run in a hook context.

Privacy invariants (see docs/rfcs/0001-agora-feedback-loop.md):
- Capture is OFF by default; ``enable`` is explicit.
- The spool lives in ~/.agora, outside any project root, and never
  leaves the machine.
- Only invocations whose plugin prefix proves them to be Agora skills
  are recorded; personal and third-party skills never enter the spool.
- ``submit`` transmits only when a previous, separate ``submit`` printed
  the byte-identical payload for review inside the confirmation window.
- AGORA_FEEDBACK=0 disables everything; the ``capture`` hook entry
  point always exits 0 so a broken pipeline never blocks a session.
"""

import argparse
import hashlib
import json
import os
import re
import secrets
import shutil
import subprocess
import sys
import time
import uuid
from datetime import date, datetime
from pathlib import Path

SCHEMA_VERSION = 1
POLICY_VERSION = 1
HUB_REPO = "rpatrik96/research-agora"
ISSUE_LABEL = "skill-feedback"
SKILL_NAMES_FILE = "skill-names.json"  # generated by scripts/generate-registry.py
PLUGIN_NAMES_FILE = "plugin-names.json"  # generated by scripts/generate-registry.py
SPOOL_RETENTION_DAYS = 90
# The capture hook prunes the on-disk spool at most once a day, so retention
# costs one file rewrite per day instead of one per captured event.
SPOOL_PRUNE_INTERVAL_SECONDS = 86400
# How long a reviewed payload stays confirmable. Fifteen minutes covers
# reading a payload of a few dozen lines and answering; it expires well
# inside the working session, so a preview left open in another terminal
# cannot authorize a send later.
SUBMIT_TOKEN_TTL_SECONDS = 900
INSIGHT_TYPES = (
    "bug",
    "improvement",
    "docs-gap",
    "missing-skill",
    "overlap",
    "deprecation-signal",
    "praise",
)
ERROR_CODES = (
    "INVALID_INPUT",
    "TIMEOUT",
    "SERVICE_UNAVAILABLE",
    "SCOPE_EXCEEDED",
    "CONFIDENCE_LOW",
    "PARTIAL_RESULT",
)
INSIGHT_TEXT_MAX = 500

# PII lint: block emails, home paths, and URLs carrying credential-shaped
# query parameters from ever entering a report.
#
# The home-directory pattern accepts any Windows drive letter and matches
# case-insensitively like the URL pattern beside it: hardcoding C: and
# matching case-sensitively let `D:\Users\...` and `/users/...` through
# unflagged (finding 5).
#
# The URL pattern allows word characters, dots, and hyphens around the
# credential keyword, because the real OAuth and API conventions are compound
# names. Requiring the keyword to sit immediately after ? or & caught only
# bare `?token=` and passed `?access_token=`, `?api_key=`, `?client_secret=`,
# and `?auth_token=` (finding 2). Substring matching also flags innocent
# parameters that contain a keyword (`?monkey=`), which is the right way to
# be wrong here: the finding is a warning at insight-add time and a block at
# submit that --allow-pii can override.
PII_PATTERNS = (
    ("email address", re.compile(r"[\w.+-]+@[\w-]+\.[\w.]+")),
    (
        "home directory path",
        re.compile(r"(?:/home/|/Users/|[A-Za-z]:\\Users\\)\S+", re.I),
    ),
    (
        "URL with token-like query",
        re.compile(
            r"https?://\S*[?&][\w.-]*(?:token|key|secret|password|auth)[\w.-]*=", re.I
        ),
    ),
)

# Control characters never belong in a payload bound for a public issue.
# The aggregator rejects them (scripts/aggregate-feedback.py), but that runs
# weekly over already-published issues, so without a client-side check an
# ANSI escape or a NUL sits in a live public issue until then — and
# `insight list` prints insight text straight to a terminal (finding 3).
CONTROL_CHARS_RE = re.compile(r"[\x00-\x1f\x7f]")


def agora_home() -> Path:
    return Path(os.environ.get("AGORA_HOME", str(Path.home() / ".agora")))


def config_path() -> Path:
    return agora_home() / "config.json"


def spool_path() -> Path:
    return agora_home() / "spool" / "events.jsonl"


def archive_dir() -> Path:
    return agora_home() / "spool" / "archive"


def reports_dir() -> Path:
    return agora_home() / "reports"


def pending_report_path() -> Path:
    return reports_dir() / "pending-report.json"


def submit_token_path() -> Path:
    """Record of the payload the user last had printed for review."""
    return reports_dir() / "submit-token.json"


def pending_cutoff_path() -> Path:
    """Newest spool timestamp the pending report covers.

    Kept beside the report rather than inside it: the report is published,
    and reports carry day precision only (RFC-0001 §7).
    """
    return reports_dir() / "pending-cutoff.json"


def prune_stamp_path() -> Path:
    """Marker whose mtime throttles on-disk spool pruning."""
    return agora_home() / "spool" / ".last-prune"


def secure_mkdir(path: Path) -> None:
    """Create a directory tree and keep ~/.agora private to the user."""
    path.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(agora_home(), 0o700)
    except OSError:
        pass


def load_config() -> dict:
    try:
        with open(config_path()) as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}


def save_config(config: dict) -> None:
    secure_mkdir(config_path().parent)
    with open(config_path(), "w") as f:
        json.dump(config, f, indent=2)


def kill_switch_active() -> bool:
    return os.environ.get("AGORA_FEEDBACK", "") == "0"


def submissions_disabled() -> bool:
    return os.environ.get("CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC", "") == "1"


def capture_enabled() -> bool:
    return not kill_switch_active() and load_config().get("enabled", False) is True


def registry_index_path() -> Path | None:
    """Locate registry/index.json across every layout the client ships in.

    A marketplace checkout (repo, or ~/.claude/plugins/marketplaces/<name>/)
    keeps the registry above the script, so walking up finds it. The plugin
    cache — ~/.claude/plugins/cache/<marketplace>/<plugin>/<version>/scripts/ —
    holds plugin directories only, and nothing above the script is the
    marketplace root; there we cross over to the sibling checkout by name.
    """
    here = Path(__file__).resolve()
    parents = list(here.parents)
    for parent in parents:
        candidate = parent / "registry" / "index.json"
        if candidate.is_file():
            return candidate
    for i, parent in enumerate(parents):
        if parent.name == "cache" and i > 0:
            candidate = (
                parent.parent
                / "marketplaces"
                / parents[i - 1].name
                / "registry"
                / "index.json"
            )
            if candidate.is_file():
                return candidate
    return None


def marketplace_root() -> Path | None:
    """Root of the marketplace checkout, when one is reachable."""
    index = registry_index_path()
    return index.parent.parent if index else None


def marketplace_manifest_path() -> Path | None:
    """Locate .claude-plugin/marketplace.json in the resolved checkout."""
    root = marketplace_root()
    if root is None:
        return None
    candidate = root / ".claude-plugin" / "marketplace.json"
    return candidate if candidate.is_file() else None


def load_skill_names(path: Path) -> set[str]:
    """Names from either a registry index or the shipped name manifest."""
    try:
        with open(path) as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        return set()
    if isinstance(data, dict) and "repos" in data:
        try:
            return {
                s["name"]
                for repo in data.get("repos", [])
                for s in repo.get("skills", [])
            }
        except (KeyError, TypeError):
            return set()
    if isinstance(data, dict) and isinstance(data.get("names"), list):
        return {n for n in data["names"] if isinstance(n, str)}
    return set()


_KNOWN_SKILLS: set[str] | None = None


def known_skill_names() -> set[str]:
    """Skill and agent names this marketplace owns.

    Fails CLOSED: an unresolvable registry yields an empty set, so capture
    records nothing rather than everything. The reverse — recording any skill
    invocation when the registry is missing — leaked personal and third-party
    skill names into public reports from the plugin-cache layout, where the
    registry never resolved (issue #25).

    Sources, in order: an explicit AGORA_SKILL_NAMES_FILE override (tests),
    the marketplace registry, then skill-names.json shipped beside this script
    so the cache layout has a list of its own.
    """
    global _KNOWN_SKILLS
    if _KNOWN_SKILLS is not None:
        return _KNOWN_SKILLS
    sources = []
    override = os.environ.get("AGORA_SKILL_NAMES_FILE")
    if override:
        sources.append(Path(override))
    index = registry_index_path()
    if index:
        sources.append(index)
    sources.append(Path(__file__).resolve().parent / SKILL_NAMES_FILE)
    for source in sources:
        names = load_skill_names(source)
        if names:
            _KNOWN_SKILLS = names
            return names
    _KNOWN_SKILLS = set()
    return _KNOWN_SKILLS


def load_plugin_names(path: Path) -> set[str]:
    """Names from either the marketplace manifest or the shipped name list."""
    try:
        with open(path) as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        return set()
    if not isinstance(data, dict):
        return set()
    if isinstance(data.get("plugins"), list):
        return {
            p["name"]
            for p in data["plugins"]
            if isinstance(p, dict) and isinstance(p.get("name"), str)
        }
    if isinstance(data.get("names"), list):
        return {n for n in data["names"] if isinstance(n, str)}
    return set()


_KNOWN_PLUGINS: set[str] | None = None


def known_plugin_names() -> set[str]:
    """Plugin names this marketplace owns.

    Fails CLOSED for the same reason known_skill_names() does: with no plugin
    list, no invocation can be attributed to the Agora, so capture records
    nothing.

    Sources, in order: an explicit AGORA_PLUGIN_NAMES_FILE override (tests),
    the marketplace manifest, then plugin-names.json shipped beside this
    script so the plugin-cache layout — which has no marketplace root above
    it — has a list of its own.
    """
    global _KNOWN_PLUGINS
    if _KNOWN_PLUGINS is not None:
        return _KNOWN_PLUGINS
    sources = []
    override = os.environ.get("AGORA_PLUGIN_NAMES_FILE")
    if override:
        sources.append(Path(override))
    manifest = marketplace_manifest_path()
    if manifest:
        sources.append(manifest)
    sources.append(Path(__file__).resolve().parent / PLUGIN_NAMES_FILE)
    for source in sources:
        names = load_plugin_names(source)
        if names:
            _KNOWN_PLUGINS = names
            return names
    _KNOWN_PLUGINS = set()
    return _KNOWN_PLUGINS


def agora_skill_name(qualified: str) -> str | None:
    """The bare skill name, when the invocation provably belongs to the Agora.

    Hook payloads name a skill or subagent by its owning plugin
    ("development:commit", "verify:devils-advocate"). Matching the
    bare tail against the registry attributes a personal skill to the Agora
    whenever the names collide: a user's own ~/.claude/commands/commit.md is
    invoked as ``commit``, which is also the name of the development plugin's
    skill, and the collision put personal usage into a public issue. So
    provenance comes from the prefix, and the three shapes resolve as:

    - ``<agora-plugin>:<skill>`` — Agora, once the tail is in the registry.
    - ``<other-plugin>:<skill>`` — another marketplace's; drop it.
    - ``<skill>`` — unattributable, so dropped too. This is narrower than the
      filter issue #25 installed, deliberately: a bare name is evidence of
      nothing, and capture that cannot prove provenance records nothing.

    The rule applies per invocation, never per session: a personal command
    that dispatches ``verify:devils-advocate`` is itself bare and
    dropped, while the Agora agent it dispatches stays attributable and is
    recorded.
    """
    plugin, separator, bare = qualified.partition(":")
    if not separator:
        return None
    if plugin not in known_plugin_names():
        return None
    if bare not in known_skill_names():
        return None
    return bare


def detect_error_code(text: str) -> str | None:
    for code in ERROR_CODES:
        if code in text:
            return code
    return None


def event_from_hook_payload(payload: dict) -> dict | None:
    """Translate a Claude Code hook payload into a spool event, or None."""
    hook_event = payload.get("hook_event_name", "")
    session = str(payload.get("session_id", ""))[:8] or "unknown"

    if hook_event == "SessionEnd":
        return {"event": "session_end", "session": session}

    tool = payload.get("tool_name", "")
    tool_input = payload.get("tool_input") or {}
    if tool == "Skill":
        skill = tool_input.get("skill") or tool_input.get("name")
        event_type = "invocation"
    elif tool in ("Task", "Agent"):
        skill = tool_input.get("subagent_type")
        event_type = "subagent"
    else:
        return None
    if not skill:
        return None

    skill = agora_skill_name(str(skill))
    if skill is None:
        return None  # unattributable, foreign, or no name list: record nothing

    response = payload.get("tool_response")
    response_text = (
        json.dumps(response)
        if isinstance(response, (dict, list))
        else str(response or "")
    )
    error_code = detect_error_code(response_text)
    if isinstance(response, dict) and ("error" in response or response.get("is_error")):
        outcome = "error"
    elif error_code == "PARTIAL_RESULT":
        outcome = "partial"
    elif error_code:
        outcome = "error"
    else:
        outcome = "success"

    return {
        "event": event_type,
        "session": session,
        "skill": skill,
        "outcome": outcome,
        "error_code": error_code,
        "duration_bucket": None,
        "model": None,
    }


def write_spool_lines(lines: list[str]) -> None:
    """Replace the spool atomically, the way purge_unknown_skills does.

    A temp file in the same directory plus os.replace() means a crash
    mid-write leaves the previous spool intact. The pid suffix keeps two
    concurrent rewrites from sharing one temp path.
    """
    spool = spool_path()
    secure_mkdir(spool.parent)
    tmp = spool.with_suffix(f".{os.getpid()}.tmp")
    tmp.write_text("".join(f"{line}\n" for line in lines))
    os.replace(tmp, spool)


def prune_spool() -> None:
    """Drop events older than the retention window from DISK.

    read_spool() filtered by age at read time, so the 90-day rolling
    retention of RFC-0001 §7 held in memory only: a user who enabled capture
    and never submitted kept every event on disk forever, since the spool
    file shrank only when a successful submit archived it (finding 6).

    Lines whose timestamp is missing or unparseable go with the expired ones.
    They can never enter a report — read_spool() already discards them — so
    keeping them live would grow the file without bound.
    """
    spool = spool_path()
    if not spool.exists():
        return
    cutoff = datetime.now().timestamp() - SPOOL_RETENTION_DAYS * 86400
    kept = []
    dropped = 0
    for line in spool.read_text().splitlines():
        if not line.strip():
            continue
        try:
            fresh = datetime.fromisoformat(json.loads(line)["ts"]).timestamp() >= cutoff
        except (json.JSONDecodeError, KeyError, TypeError, ValueError):
            fresh = False
        if fresh:
            kept.append(line)
        else:
            dropped += 1
    if dropped:
        write_spool_lines(kept)


def prune_due() -> bool:
    """True at most once per SPOOL_PRUNE_INTERVAL_SECONDS.

    Rewriting the spool on every captured event would put a full file rewrite
    in the hot path of every skill invocation, which RFC-0001 §4.4 forbids.
    Stamping first means a failed prune waits for the next interval instead
    of retrying on every event.
    """
    stamp = prune_stamp_path()
    try:
        if time.time() - stamp.stat().st_mtime < SPOOL_PRUNE_INTERVAL_SECONDS:
            return False
    except OSError:
        pass
    try:
        stamp.parent.mkdir(parents=True, exist_ok=True)
        stamp.touch()
    except OSError:
        return False
    return True


def cmd_capture() -> int:
    """Hook entry point. Must never fail and never block."""
    try:
        if not capture_enabled():
            return 0
        payload = json.load(sys.stdin)
        event = event_from_hook_payload(payload)
        if event is None:
            return 0
        event["ts"] = datetime.now().isoformat(timespec="seconds")
        secure_mkdir(spool_path().parent)
        with open(spool_path(), "a") as f:
            f.write(json.dumps(event) + "\n")
        # Retention runs here, throttled, and inside this blanket guard: a
        # failed prune can neither change the hook's exit code nor lose the
        # event just appended.
        if prune_due():
            prune_spool()
    except Exception:
        pass
    return 0


def read_spool() -> list[dict]:
    events = []
    try:
        with open(spool_path()) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    events.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    except OSError:
        return []
    cutoff = datetime.now().timestamp() - SPOOL_RETENTION_DAYS * 86400
    kept = []
    for e in events:
        try:
            if datetime.fromisoformat(e["ts"]).timestamp() >= cutoff:
                kept.append(e)
        except (KeyError, ValueError):
            continue
    return kept


def aggregate_spool(events: list[dict]) -> dict:
    """Per-skill counters from spool events (day precision, content-free)."""
    skills: dict[str, dict] = {}
    sessions = set()
    days = []
    for e in events:
        sessions.add(e.get("session"))
        days.append(e["ts"][:10])
        if e.get("event") == "session_end":
            continue
        s = skills.setdefault(
            e["skill"],
            {
                "invocations": 0,
                "outcomes": {"success": 0, "partial": 0, "error": 0, "unknown": 0},
                "error_codes": {},
                "duration_buckets": {},
                "models": {},
            },
        )
        s["invocations"] += 1
        s["outcomes"][e.get("outcome", "unknown")] = (
            s["outcomes"].get(e.get("outcome", "unknown"), 0) + 1
        )
        for key, field in (
            ("error_code", "error_codes"),
            ("duration_bucket", "duration_buckets"),
            ("model", "models"),
        ):
            value = e.get(key)
            if value:
                s[field][value] = s[field].get(value, 0) + 1
    return {
        "skills": skills,
        "sessions": len(sessions),
        "from": min(days) if days else None,
        "to": max(days) if days else None,
    }


def git_short_sha(repo: Path, path: str | None = None) -> str | None:
    cmd = ["git", "-C", str(repo), "log", "-1", "--format=%h"]
    if path:
        cmd += ["--", path]
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
        sha = out.stdout.strip()
        return sha or None
    except (OSError, subprocess.SubprocessError):
        return None


def events_cutoff(events: list[dict]) -> str | None:
    """Newest full-precision timestamp among the events a report covers.

    Submission archives up to this mark, so events captured after the report
    was built stay live for the next cycle (finding 7).
    """
    stamps = [e["ts"] for e in events if isinstance(e.get("ts"), str)]
    return max(stamps) if stamps else None


def build_report(events: list[dict] | None = None) -> dict:
    """Assemble the report payload from spool events.

    Callers that also need the coverage cutoff pass the same event list they
    read, so the cutoff describes exactly the events the report counted.
    """
    config = load_config()
    events = read_spool() if events is None else events
    agg = aggregate_spool(events)
    root = marketplace_root()

    skill_entries = []
    for name in sorted(agg["skills"]):
        counters = agg["skills"][name]
        entry = {"skill": name, "skill_sha": None, **counters, "insights": []}
        skill_entries.append(entry)

    marketplace_sha = git_short_sha(root) if root else None
    if marketplace_sha:
        paths = {}
        try:
            with open(registry_index_path()) as f:
                for repo in json.load(f).get("repos", []):
                    for s in repo.get("skills", []):
                        paths[s["name"]] = s.get("path")
        except (OSError, TypeError, json.JSONDecodeError):
            pass
        for entry in skill_entries:
            skill_file = paths.get(entry["skill"])
            if skill_file:
                entry["skill_sha"] = git_short_sha(root, skill_file)

    return {
        "schema_version": SCHEMA_VERSION,
        "report_id": f"r-{uuid.uuid4()}",
        "created": date.today().isoformat(),
        "reporter": {
            "installation_id": config.get("installation_id"),
            "client": "claude-code",
            "marketplace_sha": marketplace_sha,
        },
        "period": {"from": agg["from"], "to": agg["to"], "sessions": agg["sessions"]},
        "consent": {
            "reviewed": False,
            "channel": config.get("sink", "github-issue"),
            "policy_version": POLICY_VERSION,
        },
        "skills": skill_entries,
        "environment": {"os": sys.platform},
    }


def pii_findings(report: dict) -> list[str]:
    findings = []
    for entry in report.get("skills", []):
        for insight in entry.get("insights", []):
            for label, pattern in PII_PATTERNS:
                if pattern.search(insight.get("text", "")):
                    findings.append(
                        f"{entry['skill']}: insight contains {label}: {insight['text'][:80]!r}"
                    )
    return findings


def control_char_findings(report: dict) -> list[str]:
    """Strings in the payload carrying control characters (finding 3).

    The scan covers every string in the payload rather than insight text
    alone, because the whole payload is what gets published, and a
    hand-edited pending report is not bound by the insight-add check.
    """
    findings = []

    def walk(node, path: str) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                walk(value, f"{path}.{key}" if path else str(key))
        elif isinstance(node, list):
            for index, value in enumerate(node):
                walk(value, f"{path}[{index}]")
        elif isinstance(node, str) and CONTROL_CHARS_RE.search(node):
            findings.append(f"{path or 'payload'}: control characters in {node[:80]!r}")

    walk(report, "")
    return findings


def load_pending() -> dict | None:
    try:
        with open(pending_report_path()) as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return None


def save_pending(report: dict) -> None:
    secure_mkdir(reports_dir())
    with open(pending_report_path(), "w") as f:
        json.dump(report, f, indent=2)


def save_pending_cutoff(report: dict, cutoff: str | None) -> None:
    secure_mkdir(reports_dir())
    with open(pending_cutoff_path(), "w") as f:
        json.dump({"report_id": report["report_id"], "cutoff": cutoff}, f, indent=2)


def load_pending_cutoff(report: dict) -> str | None:
    """The cutoff recorded for this exact report, or None.

    None also covers a pending report written by an older client, where
    submission falls back to archiving the whole spool.
    """
    try:
        with open(pending_cutoff_path()) as f:
            record = json.load(f)
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(record, dict) or record.get("report_id") != report.get(
        "report_id"
    ):
        return None
    cutoff = record.get("cutoff")
    return cutoff if isinstance(cutoff, str) else None


def cmd_enable() -> int:
    config = load_config()
    if not config.get("installation_id"):
        config["installation_id"] = secrets.token_hex(16)
    config.update(
        {
            "enabled": True,
            "sink": config.get("sink", "github-issue"),
            "created": config.get("created", date.today().isoformat()),
        }
    )
    save_config(config)
    print(
        "Agora feedback capture ENABLED (local only — nothing is ever sent automatically)."
    )
    print(f"  config: {config_path()}")
    print(f"  spool:  {spool_path()}")
    print(
        f"  installation_id: {config['installation_id']} (random; reset by deleting the config)"
    )
    return 0


def cmd_disable() -> int:
    config = load_config()
    config["enabled"] = False
    save_config(config)
    # The capture hook is the throttled pruner, and it stops running here, so
    # enforce retention once on the way out (finding 6).
    prune_spool()
    print(
        "Agora feedback capture disabled. Existing spool kept; run 'purge' to delete it."
    )
    return 0


def cmd_status() -> int:
    config = load_config()
    # Unthrottled: status is a user-invoked command, not the hook, and the
    # count it prints should describe what is actually on disk.
    prune_spool()
    events = read_spool()
    print(f"enabled:            {config.get('enabled', False)}")
    print(
        f"kill switch:        {'AGORA_FEEDBACK=0 (capture disabled)' if kill_switch_active() else 'not set'}"
    )
    print(
        f"submissions:        {'disabled (CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1)' if submissions_disabled() else 'allowed after review'}"
    )
    print(f"sink:               {config.get('sink', 'github-issue')}")
    print(f"spool events:       {len(events)} ({spool_path()})")
    print(f"pending report:     {'yes' if load_pending() else 'no'}")
    return 0


def cmd_stats() -> int:
    agg = aggregate_spool(read_spool())
    if not agg["skills"]:
        print("Spool is empty — no Agora skill usage captured yet.")
        return 0
    print(
        f"Local usage {agg['from']} → {agg['to']} ({agg['sessions']} sessions). Nothing here has been sent anywhere.\n"
    )
    print(f"{'skill':<32} {'calls':>5} {'ok':>4} {'part':>4} {'err':>4}")
    for name in sorted(agg["skills"], key=lambda n: -agg["skills"][n]["invocations"]):
        o = agg["skills"][name]["outcomes"]
        print(
            f"{name:<32} {agg['skills'][name]['invocations']:>5} "
            f"{o.get('success', 0):>4} {o.get('partial', 0):>4} {o.get('error', 0):>4}"
        )
    return 0


def cmd_report() -> int:
    events = read_spool()
    report = build_report(events)
    if not report["skills"]:
        print("Spool is empty — nothing to report.")
        return 1
    existing = load_pending()
    if existing:  # keep user-curated insights across rebuilds
        insights = {
            e["skill"]: e.get("insights", []) for e in existing.get("skills", [])
        }
        for entry in report["skills"]:
            entry["insights"] = insights.get(entry["skill"], [])
    save_pending(report)
    save_pending_cutoff(report, events_cutoff(events))
    print(json.dumps(report, indent=2))
    print(f"\nPending report written to {pending_report_path()}", file=sys.stderr)
    print(
        "Add insights with: insight add <skill> <type> <text> [--confidence X]",
        file=sys.stderr,
    )
    return 0


def cmd_insight(args: argparse.Namespace) -> int:
    report = load_pending()
    if report is None:
        print("No pending report. Run 'report' first.")
        return 1
    if args.insight_action == "list":
        for entry in report["skills"]:
            for i, insight in enumerate(entry.get("insights", [])):
                print(f"{entry['skill']}[{i}] ({insight['type']}): {insight['text']}")
        return 0
    entries = {e["skill"]: e for e in report["skills"]}
    if args.skill not in entries:
        print(
            f"Skill '{args.skill}' is not in the pending report ({', '.join(sorted(entries))})."
        )
        return 1
    if args.insight_action == "add":
        if args.type not in INSIGHT_TYPES:
            print(f"Invalid type '{args.type}'. Valid: {', '.join(INSIGHT_TYPES)}")
            return 1
        text = args.text.strip()[:INSIGHT_TEXT_MAX]
        if CONTROL_CHARS_RE.search(text):
            # Rejected outright rather than warned about, unlike the PII
            # patterns: no insight needs a terminal escape or a NUL, the
            # aggregator discards the whole report over one, and `insight
            # list` would print it raw to a terminal (finding 3).
            print(
                "Rejected: insight text contains control characters "
                "(terminal escapes or NUL). Retype it as plain text."
            )
            return 1
        insight = {"type": args.type, "text": text, "confidence": args.confidence}
        entries[args.skill].setdefault("insights", []).append(insight)
        for label, pattern in PII_PATTERNS:
            if pattern.search(text):
                print(
                    f"WARNING: insight text contains a possible {label} — submit will block on it."
                )
    elif args.insight_action == "remove":
        insights = entries[args.skill].get("insights", [])
        if not 0 <= args.index < len(insights):
            print(f"No insight at index {args.index} for '{args.skill}'.")
            return 1
        insights.pop(args.index)
    save_pending(report)
    print("Pending report updated.")
    return 0


def archive_spool(cutoff: str | None = None) -> None:
    """Archive the events the submitted report covered, keeping the rest.

    Moving the whole spool swept every event captured between building the
    report and confirming the submission: they were archived without ever
    appearing in a submitted report, so the next report under-counted them
    (finding 7). Events newer than the cutoff stay live for the next cycle.

    A missing cutoff (a pending report from an older client) falls back to
    archiving everything, the prior behaviour: under-counting a handful of
    in-between events beats re-reporting events the aggregate already holds.
    """
    spool = spool_path()
    if not spool.exists():
        return
    secure_mkdir(archive_dir())
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    destination = archive_dir() / f"events-{stamp}.jsonl"
    if cutoff is None:
        shutil.move(str(spool), str(destination))
        return

    archived = []
    kept = []
    for line in spool.read_text().splitlines():
        if not line.strip():
            continue
        try:
            ts = json.loads(line).get("ts")
        except json.JSONDecodeError:
            ts = None
        # A line with no usable timestamp can never enter a report, so it is
        # archived rather than kept live forever.
        if isinstance(ts, str) and ts > cutoff:
            kept.append(line)
        else:
            archived.append(line)
    with open(destination, "a") as f:
        f.write("".join(f"{line}\n" for line in archived))
    write_spool_lines(kept)


def issue_body(report: dict) -> str:
    return (
        "Automated skill-feedback report (RFC-0001). Reviewed and submitted by the reporter.\n\n"
        "```json\n" + json.dumps(report, indent=2) + "\n```\n"
    )


def payload_digest(report: dict) -> str:
    """SHA-256 of the exact issue body this report would be submitted as.

    The confirmation token commits to this digest, so the payload the user
    reviewed is provably the payload that gets sent.
    """
    return hashlib.sha256(issue_body(report).encode("utf-8")).hexdigest()


def record_submit_token(report: dict) -> None:
    """Record that this exact payload was printed for review (finding 4)."""
    secure_mkdir(reports_dir())
    token = {
        "report_id": report["report_id"],
        "payload_sha256": payload_digest(report),
        "issued": int(time.time()),
    }
    with open(submit_token_path(), "w") as f:
        json.dump(token, f, indent=2)


def submit_token_refusal(report: dict) -> str | None:
    """None when a fresh review of this exact payload authorizes the send.

    Otherwise the reason to refuse. The preview-then-confirm gate of
    RFC-0001 §4.2 and §8 was prose only: cmd_submit printed the payload and
    then read the flag, so a bare ``submit --confirm`` printed and sent in
    one invocation, with nothing binding a prior review to a later
    confirmation. The token makes the two invocations structurally separate.
    Binding it to the payload digest means an edited report needs a new
    review; the TTL means a review from hours ago cannot authorize a send.
    """
    try:
        with open(submit_token_path()) as f:
            token = json.load(f)
    except (OSError, json.JSONDecodeError):
        return "no reviewed payload on record"
    if not isinstance(token, dict):
        return "the confirmation record is unreadable"
    if token.get("report_id") != report.get("report_id"):
        return "the reviewed payload belonged to a different report"
    if token.get("payload_sha256") != payload_digest(report):
        return "the report changed after it was reviewed"
    issued = token.get("issued")
    if isinstance(issued, bool) or not isinstance(issued, (int, float)):
        return "the confirmation record has no usable timestamp"
    age = time.time() - issued
    if age < 0 or age > SUBMIT_TOKEN_TTL_SECONDS:
        return (
            f"the review is stale (older than {SUBMIT_TOKEN_TTL_SECONDS // 60} minutes)"
        )
    return None


def cmd_submit(confirm: bool, allow_pii: bool) -> int:
    report = load_pending()
    if report is None:
        print("No pending report. Run 'report' first, review it, then submit.")
        return 1

    findings = pii_findings(report)
    if findings and not allow_pii:
        print("Submission BLOCKED — possible personal data in insights:")
        for finding in findings:
            print(f"  - {finding}")
        print(
            "Edit the insights (insight remove/add) or re-run with --allow-pii to override."
        )
        return 1

    control = control_char_findings(report)
    if control:
        print("Submission BLOCKED — control characters in the payload:")
        for finding in control:
            print(f"  - {finding}")
        print(
            "Rewrite the affected text as plain text. --allow-pii does not "
            "override this, and the aggregator rejects such a report anyway."
        )
        return 1

    report["consent"]["reviewed"] = True
    print("=== EXACT PAYLOAD TO BE SUBMITTED ===")
    print(json.dumps(report, indent=2))
    print("=====================================")

    if not confirm:
        record_submit_token(report)
        print(
            "\nNothing was sent. Review the payload above; to send exactly it, re-run "
            f"within {SUBMIT_TOKEN_TTL_SECONDS // 60} minutes: submit --confirm"
        )
        return 0
    # Kill switches outrank everything, including the state of the review
    # gate, so they answer first (RFC-0001 §8).
    if submissions_disabled():
        print("Submission refused: CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 is set.")
        return 1
    if kill_switch_active():
        print("Submission refused: AGORA_FEEDBACK=0 is set.")
        return 1
    refusal = submit_token_refusal(report)
    if refusal:
        print(f"Submission refused: {refusal}.")
        print(
            "Run 'submit' first, read the exact payload it prints, then re-run "
            "'submit --confirm' to send that payload. Nothing was sent."
        )
        return 1

    save_pending(report)
    body = issue_body(report)
    title = f"[Feedback] {report['report_id']} ({report['period']['from']} → {report['period']['to']})"
    base_cmd = [
        "gh",
        "issue",
        "create",
        "--repo",
        HUB_REPO,
        "--title",
        title,
        "--body",
        body,
    ]
    result = None
    # First try with the label; if that fails (e.g. label missing in the
    # repo), retry unlabeled — the aggregator's title-prefix is not enough,
    # but a maintainer can label it, and losing the report entirely is worse.
    for cmd in (base_cmd + ["--label", ISSUE_LABEL], base_cmd):
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        except (OSError, subprocess.SubprocessError):
            result = None
        if result is not None and result.returncode == 0:
            break

    if result is not None and result.returncode == 0:
        receipt = result.stdout.strip()
        print(f"Submitted: {receipt}")
    else:
        manual = reports_dir() / f"submit-{report['report_id']}.md"
        manual.write_text(body)
        print("Could not submit via the GitHub CLI (gh). Manual fallback:")
        print(
            f"  1. Open https://github.com/{HUB_REPO}/issues/new?template=skill-feedback.yml"
        )
        print(f"  2. Paste the contents of {manual}")
        print(
            "The spool was NOT archived; re-run submit --confirm after posting "
            "(run 'submit' again first if the review window has lapsed), or "
            "archive manually."
        )
        return 1

    archive_spool(load_pending_cutoff(report))
    submitted = reports_dir() / f"submitted-{report['report_id']}.json"
    shutil.move(str(pending_report_path()), str(submitted))
    # The review authorized this one send: consume it, and drop the coverage
    # mark with the report it belonged to.
    for path in (submit_token_path(), pending_cutoff_path()):
        try:
            path.unlink()
        except OSError:
            pass
    print(f"Spool archived; report stored at {submitted}")
    return 0


def purge_unknown_skills() -> int:
    """Drop spool events and pending-report entries for non-Agora skills.

    Repairs a spool written while the registry filter was disabled, without
    discarding the legitimate history alongside it.
    """
    known = known_skill_names()
    if not known:
        print(
            "No skill name list available — refusing to purge, since every "
            "skill would count as unknown."
        )
        return 1

    dropped: dict[str, int] = {}
    spool = spool_path()
    if spool.exists():
        kept_lines = []
        for line in spool.read_text().splitlines():
            if not line.strip():
                continue
            try:
                event = json.loads(line)
            except json.JSONDecodeError:
                continue
            skill = event.get("skill")
            if skill is not None and skill not in known:
                dropped[skill] = dropped.get(skill, 0) + 1
                continue
            kept_lines.append(line)
        write_spool_lines(kept_lines)

    report_path = pending_report_path()
    if report_path.exists():
        try:
            report = json.loads(report_path.read_text())
        except json.JSONDecodeError:
            report = None
        if report is not None:
            entries = [e for e in report.get("skills", []) if e.get("skill") in known]
            if len(entries) != len(report.get("skills", [])):
                report["skills"] = entries
                report_path.write_text(json.dumps(report, indent=2) + "\n")
                print("Pending report rewritten without the unknown skills.")

    if dropped:
        summary = ", ".join(
            f"{name} ({count})" for name, count in sorted(dropped.items())
        )
        print(f"Dropped {sum(dropped.values())} event(s) for unknown skills: {summary}")
    else:
        print("No unknown-skill events in the spool.")
    return 0


def cmd_purge(unknown_only: bool = False) -> int:
    if unknown_only:
        return purge_unknown_skills()
    removed = []
    for path in (spool_path().parent, reports_dir()):
        if path.exists():
            shutil.rmtree(path)
            removed.append(str(path))
    print("Purged: " + (", ".join(removed) if removed else "nothing to remove"))
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    for name in ("capture", "enable", "disable", "status", "stats", "report"):
        sub.add_parser(name)
    purge = sub.add_parser("purge")
    purge.add_argument(
        "--unknown-skills",
        action="store_true",
        help="drop only events for skills outside the registry, keeping the rest",
    )
    submit = sub.add_parser("submit")
    submit.add_argument("--confirm", action="store_true")
    submit.add_argument("--allow-pii", action="store_true")
    insight = sub.add_parser("insight")
    insight_sub = insight.add_subparsers(dest="insight_action", required=True)
    insight_sub.add_parser("list")
    add = insight_sub.add_parser("add")
    add.add_argument("skill")
    add.add_argument("type")
    add.add_argument("text")
    add.add_argument("--confidence", type=float, default=0.5)
    remove = insight_sub.add_parser("remove")
    remove.add_argument("skill")
    remove.add_argument("index", type=int)

    args = parser.parse_args(argv)
    if args.command == "capture":
        return cmd_capture()
    if args.command == "enable":
        return cmd_enable()
    if args.command == "disable":
        return cmd_disable()
    if args.command == "status":
        return cmd_status()
    if args.command == "stats":
        return cmd_stats()
    if args.command == "report":
        return cmd_report()
    if args.command == "insight":
        return cmd_insight(args)
    if args.command == "submit":
        return cmd_submit(confirm=args.confirm, allow_pii=args.allow_pii)
    if args.command == "purge":
        return cmd_purge(unknown_only=args.unknown_skills)
    return 2


if __name__ == "__main__":
    sys.exit(main())
